# path and dir

data_dir: "./data"
answer_path: "./data/answers"
question_path: "./src/questions.json"
alias_path: "./config/alias_command.txt"
study_help_path: "./config/study-help.txt"
gui_help_path: "./config/gui-help.txt"
record_help_path: "./config/record-help.txt"
gui_plan_dir: "/data/guangji.huang/mygithub/everyday-record"
timer_gui_pipeline_path: "/data/guangji.huang/win-linux-communicate/pipeline.txt"

# init file type
file_type: "question"

# init study data
topic1: "tool"
topic2: "linux"
question_id: 9
